export default [
  {
    id: 1,
    csnumber: "01",
    cstitle: "echo",
    texttop:
      "A live captioning mobile app designed for accessibility and inclusivity.",
    textbottom: "UX + UI Design | Front-End Development | Interaction Design",
    linkout: "/russell_portfolio/work/echo",
    border: false,
    space: false,
    backgroundcolor: "#98CBBD",
  },
  {
    id: 2,
    csnumber: "02",
    cstitle: "Starting Over Inc.",
    texttop: "Website redesign for local nonprofit organization.",
    textbottom: "UX + UI Design | Research | Prototyping",
    linkout: "/russell_portfolio/work/starting-over-inc",
    border: false,
    space: true,
    backgroundcolor: "#384B2F",
  },
  {
    id: 3,
    csnumber: "03",
    cstitle: "Envision",
    texttop: "A mobile travel planning application.",
    textbottom: "UX + UI Design | Branding | Prototyping",
    linkout: "/russell_portfolio/work/envision",
    border: false,
    space: true,
    backgroundcolor: "#FACE32",
  },
  {
    id: 4,
    csnumber: "04",
    cstitle: "Hatch",
    texttop: "A mobile financial planning and budgeting application.",
    textbottom: "UX + UI Design | Research | Branding",
    linkout: "/russell_portfolio/work/hatch",
    border: false,
    space: true,
    backgroundcolor: "#35591C",
  },
  {
    id: 5,
    csnumber: "05",
    cstitle: "FDA",
    texttop: "Website redesign for The U.S. Food and Drug Administration.",
    textbottom: "UX + UI Design | Research | Prototyping",
    linkout: "/russell_portfolio/work/fda",
    border: true,
    space: true,
    backgroundcolor: "#36598D",
  },
];
